"""add Task model

Revision ID: 00410106a874
Revises: 008b4ddbafd9
Create Date: 2024-10-31 16:15:22.818542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00410106a874'
down_revision = '008b4ddbafd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='goal_pkey')
    )
    # ### end Alembic commands ###
